### ISSUE TITLE
Übernimmt die GamUserSettings.ini einstellungen nicht

### ISSUE THREAD

**Issue by Crizzle1988** [Zerschranzer/Ark-Survival-ascended-dedicated-server-without-docker#3]
Hallo, 

ich habe die GameUserSettings mit ein paar Befehlen gefüttert, auch die Anzahl der Spieler. Jedoch werden keine der Einstellungen übernommen. Die Einträge aus der Instance ini werden bis auf die Spieleranzahl aber übernommen.

**Comment by Zerschranzer** [comment]
Alle Einstellungen für die jeweilige Instanz sind in der Datei `/instances/<deineinstanz>/instance_config.ini` festgelegt. Wenn die dort definierten Einstellungen mit der `GameUserSettings.ini` in Konflikt geraten, haben die Einstellungen aus der `instance_config.ini` Vorrang, da sie als Startparameter an die Instanz übergeben werden.

Jede Instanz hat außerdem ihre eigene `GameUserSettings.ini` im Ordner `/instances/<deineinstanz>/Config/`. Passe diese Datei für jede Instanz individuell an.

Die Funktionsweise der `start_server`-Funktion des Skripts ist wie folgt:
1. Vor jedem Serverstart erstellt das Skript ein Backup des gesamten Ordners `/server-files/ShooterGame/Saved/Config/WindowsServer/`.
2. Der Ordner wird anschließend gelöscht.
3. Ein Symlink mit dem Namen `WindowsServer` wird erstellt, der auf `/instances/<deineinstanz>/Config/` verweist.
4. Dadurch lädt der Server bei jedem Start die instanzspezifische Konfiguration aus dem entsprechenden Ordner.

---

### **Schritte zur Problemlösung:**
1. Bearbeite die Datei `/instances/<deineinstanz>/instance_config.ini` (diese hat Vorrang!).
2. Passe anschließend die `GameUserSettings.ini` in `/instances/<deineinstanz>/Config/GameUserSettings.ini` an.

---

**Falls das Problem weiterhin besteht:**
- Welche Linux-Distribution benutzt du?  
- Was steht in deiner `instance_config.ini` und in der `GameUserSettings.ini` im Abschnitt `[ServerSettings]`? (Bitte entferne sensible Daten wie Passwörter.)  
- Gibt es offensichtliche Fehlermeldungen in den Logs? (Pfad: `/server-files/ShooterGame/Saved/Logs/ShooterGame.log`)

**Comment by Zerschranzer** [comment]
Das Problem mit den MaxPlayers wurde behoben. Der Parameter ?MaxPlayers wurde durch -WinLiveMaxPlayers in den Startparametern ersetzt, da dies für ARK: Survival Ascended erforderlich ist. Bitte zieh dir die neueste Version des Skripts, um die Änderung zu erhalten.

**Comment by Crizzle1988** [comment]
Vielen Dank für die schnelle Antwort. Ich werde die Änderung morgen testen und die Einstellungen verwalten. Meine Vorgehensweise war wie folgt: 
1. Install Base Data
2. Instanz erstellen
3. Instanz starten
4. Instanz stoppen
5. Dann die GameUserSettings geändert, in dem ich Befehle hinzugefügt habe. Z.B. Harvest Amount Multiplier
6. Instanz gestartet
7. Scheint die Änderungen nicht übernommen zu haben. 
8. Die Basisdaten wie PW, Ports etc sind die aus der instance_config.ini. 


Ich nutze Debian 12 in einem LXC. 

LG

**Comment by Crizzle1988** [comment]
Hallo, Frohe Weihnachten, 

ich habs jetzt mal probiert.
Neues Script gezogen. Server gestartet aber er wird nicht gelistet. 

Shootergamelog: `[2024.12.25-11.38.57:397][  9]Server: "Dayocorp ASA Server -  TheIsland " has successfully started!
[2024.12.25-11.39.00:961][  9]Commandline:  "TheIsland_WP?listen?SessionName=Dayocorp ASA Server -  TheIsland ?MaxPlayers=5?ServerPassword=meinpwd?ServerAdminPassword=meinpwd?QueryPort=27015?Port=27020
27015
7777?RCONEnabled=True?RCONPort=27020?AltSaveDirectoryName=TheIsland" -NoBattlEye -crossplay -NoHangDetection -game -ClusterDirOverride="/home/arkserver/clusters/dayocorp" -ClusterId="mined" -server -log -mods=927090,929110,947033,928621,930494,939786,950914,967547
[2024.12.25-11.39.00:961][  9]Full Startup: 71.35 seconds
[2024.12.25-11.39.00:961][  9]Number of cores 4
[2024.12.25-11.39.15:937][244]Server has completed startup and is now advertising for join.`

vor der Scriptänderung wurde der Server noch gelistet und ich konnte ihn auswählen. 

LG

**Comment by Zerschranzer** [comment]
Hier ist der korrigierte Text:

Danke, ebenfalls frohe Weihnachten.
Zum Skript: Vor den Änderungen wurden die eingetragenen Ports falsch zugewiesen. Das wurde inzwischen korrigiert. Prüfe noch, ob die Ports in deiner Firewall korrekt geöffnet sind. Anschließend führe folgenden Befehl aus:
sudo ss -tunlp | grep wineserver
Das wird dir anzeigen, welche Ports vom Server belegt sind. Prüfe auch, ob du deinen Server auf die neueste Version aktualisiert hast.

Ich habe außerdem die ports aus der Fragezeichen schleife entfernt. Sicher das du die neueste Skript Version verwendest ? Im Log ist die Fragezeichen schleife nämlich noch zu sehen. Starte den Server Testweise auch mal ohne mods und Standard konfig. Dann füge nach und nach neue Einstellungen hinzu, um genau einzugrenzen wo das Problem liegt.

**Comment by Crizzle1988** [comment]
Hallo, 

ja hab das Script gelöscht und mit wget Befehl neugeladen, ausführbar gemacht und gestartet

**Comment by Zerschranzer** [comment]
Server geupdadet? Musst nochmal auf "Update/install base Server" klicken, da ich die proton version von 9-05 auf 9-21 geupdadet habe

**Comment by Crizzle1988** [comment]
ich update grade den Server. Dann starte ich ne neue Instanz und schau mal ob es funktioniert. 

Was mir aber aufgefallen ist, das wenn ich die Game.ini ändern will, fehlt die oberste Standardzeile.

**Comment by Zerschranzer** [comment]
Und? Läuft's inzwischen wie erwartet?

**Comment by Crizzle1988** [comment]
Hallo, 

mit dem neuen Script, klappt alles Problemlos. 
Vielen Dank für deine schnelle Änderung=). 

LG und ein guten Rutsch ins neue Jahr.

**Comment by Zerschranzer** [comment]
Danke, dir auch! :) Im ganz neuen Skript, das seit heute Nacht verfügbar ist, habe ich auch den vorhandenen RCON-Client durch meinen selbst geschriebenen ersetzt, mit dem man nun den Server "weich" herunterfahren kann. Dazu reicht es aber nicht mehr, das Skript mit `wget` herunterzuladen. Das gesamte Repository muss geklont werden. Steht aber so in der README, die ich ebenfalls komplett überarbeitet habe.
